---
version: "2"

linters:
  default: none
  enable:
    - durationcheck
    - errcheck
    - govet
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - revive
    - staticcheck
    - unconvert
    - unused
  settings:
    errcheck:
      exclude-functions:
        - github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema:ForceNew|Set
        - fmt:.*
        - io:Close
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        text: Error return value of `d.Set` is not checked
      - linters:
          - revive
        text: 'redefines-builtin-id: redefinition of the built-in'
      # TODO: Setting temporary exclusions.
      - linters:
          - staticcheck
        text: QF1001
      - linters:
          - staticcheck
        text: QF1003
      - linters:
          - staticcheck
        text: ST1005
      - linters:
          - staticcheck
        text: QF1004
      - linters:
          - staticcheck
        text: QF1011
    paths:
      - third_party$
      - builtin$
      - examples$

issues:
  max-same-issues: 0

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
